<?php
use Fuel\Core\Uri;

// ERROR OF USER
define('STATUS_OK', '200');
define('ERROR_VALIDATE', '1001');
define('ERROR_TOKEN_EXPIRED', '1002');
define('ERROR_USERNAME_PWD_NULL', '1004');
define('ERROR_LOGIN_FAILED', '1005');
define('ERROR_USERNAME_EXIST', '2001');
define('ERROR_EMAIL_EXIST', '2002');
define('ERROR_INSERT_USER', '2003');

// ERROR OF POST
define('ERROR_GET_ALL_POST_FAILED', '2501');
define('ERROR_CREATE_POST_FAILED', '2502');
define('ERROR_UPDATE_POST_FAILED', '2503');
define('ERROR_DELETE_POST_FAILED', '2504');
define('ERROR_GET_A_POST_FAILED', '2505');
define('ERROR_SEARCH_POST_FAILED', '2506');

//ERROR OF COMMENT
define('ERROR_GET_ALL_COMMENT_FAILED', '3001');
define('ERROR_CREATE_COMMENT_FAILED', '3002');
define('ERROR_UPDATE_COMMENT_FAILED', '3003');
define('ERROR_DELETE_COMMENT_FAILED', '3004');
